#? Creation
name: anomality_detection
log: false
save: true
eval_freq: 7 # * Decrease for hyper opt and final testing
eval_episodes: 50 # * Increase for hyper opt and final testing
test_episodes: 50

#? Fewshot setup

k_shot: 1
# n_way: 4
n_way: 10
n_query: 30
mix_rpms: false
mix_sensors: false
separate_query_and_support: false

#? Data

data: ARotor
train_sensors: [torque1]
validation_sensors: [torque1]
test_sensors: [torque1]

train_rpm: [250, 500, 750, 1250, 1500]
validation_rpm: [500, 1500]
test_rpm: [500, 1500]

train_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
validation_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
test_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

window_width: 4328
window_overlap: 0.99

#? Preprocessing

preprocessing_full: []
robust_scaling_low: 0.25
robust_scaling_high: 0.75
preprocessing_sample: []
preprocessing_class_batch: []
# preprocessing_batch: []
preprocessing_batch: [gain_changer, add_white_noise]
gain_std: 0.2
white_noise_std: 0.2
include_FFT_DC: false # Should the DC component of the FFC be included? Only relevant if FFT is used in some form
log_FFT: false
pad_FFT: -1
sample_cut: -1 # Done in batch preprocessing

#? Model

model: prototypical
backbone: InceptionTime
# backbone: WDCNN
kaiming_init: true
embedding_len: 16
# Lp-norm
embedding_normalization_type: lp
lp_norm: 2

embedding_multiplier: 100

#? Training

epoch_len: 1
max_epochs: 85 # FIXME?
patience: 30
optimizer: AdamW
# FIXME BELOW
lr: 0.0026877256754964493
lr_scheduler: ExponentialLR
sch_gamma: 0.9930641495748094
momentum: 0.9507914364266907
# Regularization
weight_decay: 0.00027602654261471126
label_smoothing: 0.2
cl_dropout: 0.0
fc_dropout: 0.0

# ? Other

use_amp: false  
