#? Creation
name: anomality_detection
log: false
save: true # TODO
eval_freq: 5 # * Decrease for hyper opt and final testing
eval_episodes: 20 # * Increase for hyper opt and final testing
# test_episodes: 150

#? Fewshot setup

k_shot: 1
# n_way: 4
n_way: 10
n_query: 30
mix_rpms: false
mix_sensors: false
separate_query_and_support: false

#? Data

data: ARotor
train_sensors: [acc3]
validation_sensors: [acc3]
test_sensors: [acc3]

train_rpm: [250, 500, 750, 1250, 1500]
validation_rpm: [500, 1500]
test_rpm: [500, 1500]

train_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
validation_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
test_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

window_width: 4328
window_overlap: 0.99

#? Preprocessing

preprocessing_full: []
robust_scaling_low: 0.25
robust_scaling_high: 0.75
preprocessing_sample: []
preprocessing_class_batch: []
# preprocessing_batch: []
preprocessing_batch: [add_white_noise]
gain_std: 0.0
white_noise_std: 0.2
include_FFT_DC: false # Should the DC component of the FFC be included? Only relevant if FFT is used in some form
log_FFT: false
pad_FFT: -1
sample_cut: -1 # Done in batch preprocessing

#? Model

model: prototypical
backbone: InceptionTime
# backbone: WDCNN
kaiming_init: true
embedding_len: 64
# Lp-norm
embedding_normalization_type: lp
lp_norm: 2

embedding_multiplier: 100

#? Training

epoch_len: 1
max_epochs: 200 # FIXME?
patience: 100
optimizer: AdamW
# FIXME BELOW
lr: 0.0029527578662923502
lr_scheduler: ExponentialLR
sch_gamma: 0.9616006788597983
momentum: 0.9575208310016572
# Regularization
weight_decay: 0.00003319404762312105
cl_dropout: 0.0
fc_dropout: 0.0

# ? Other

use_amp: false  
