#? Creation
name: ARotor
log: true
save: false

#? Fewshot setup

k_shot: 1
n_way: 40
n_query: 12
mix_rpms: False
mix_sensors: False
separate_query_and_support: false

#? Data

data: ARotor
train_sensors: [acc4, acc3]
validation_sensors: [acc1]
test_sensors: [acc2]
train_rpm: [750, 1000]
validation_rpm: [1000]
test_rpm: [250, 500, 1250, 1500]
train_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
validation_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
test_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
window_width: 6000
window_overlap: 0.95

#? Preprocessing

preprocessing_full: []
preprocessing_batch: []

#? Augmentation

augmentation: []

#? Model

model: prototypical
backbone: WDCNN
kaiming_init: true
embedding_len: 256
# Lp-norm
embedding_normalization_type: lp
lp_norm: 2
# Mahalanobis
# embedding_normalization_type: mahalanobis # TODO

embedding_multiplier: 1000

#? Training

max_epochs: 400
patience: 100
optimizer: AdamW
lr: 0.003
lr_scheduler: ExponentialLR
sch_gamma: 0.9998
momentum: 0.965
# Regularization
weight_decay: 0.001
cl_dropout: 0.0
fc_dropout: 0.0

# ? Other

use_amp: false