#? Creation
name: ARotor
log: true
save: false # TODO
eval_freq: 10 # * Decrease for hyper opt and final testing
eval_episodes: 10 # * Increase for hyper opt and final testing

#? Fewshot setup

k_shot: 1
n_way: 10
n_query: 18
mix_rpms: False
mix_sensors: False
separate_query_and_support: False
rpm_status: batch # XXX Only old
sensor_status: batch # XXX only old

#? Data

data: ARotor_old
train_sensors: [acc3]
validation_sensors: [acc2]
test_sensors: [acc1]
train_rpm: [250, 500, 750, 1000, 1250, 1500]
validation_rpm: [250, 500, 750, 1000, 1250, 1500]
test_rpm: [250, 500, 750, 1000, 1250, 1500]
train_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
validation_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
test_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
window_width: 6000
window_overlap: 0.95

#? Preprocessing

preprocessing_full: []
preprocessing_batch: []
FFT: True # XXX Only for old ARotor
normalize: False # XXX Only for old ARotor

#? Augmentation

augmentation: []

#? Model

model: prototypical
backbone: WDCNN_old
kaiming_init: true
embedding_len: 256
embedding_unit_len: True # XXX Only for old
embedding_normalization_type: False
# Lp-norm
# embedding_normalization_type: lp
# lp_norm: 2
# Mahalanobis
# embedding_normalization_type: mahalanobis # TODO

embedding_multiplier: 1000

#? Training

max_epochs: 500
patience: 200
optimizer: AdamW
lr: 0.003
lr_scheduler: ExponentialLR
# sch_gamma: 0.9999999
sch_gamma: 0.9998
momentum: 0.965
# Regularization
weight_decay: 0.0001
cl_dropout: 0.0
fc_dropout: 0.0

# ? Other

use_amp: false