#? Creation
name: anomality_detection_arotor

#? Data

data: ARotor

# ! Only single sensor support
# query_sensors: [torque1]
query_sensors: [acc3]

query_rpm: [250, 500, 750, 1000, 1250, 1500]

query_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

window_width: 4328

#? Model

model: prototypical
backbone: InceptionTime
# model_weight_dir: AD_ARotor_torque1_article
model_weight_dir: AD_ARotor_acc3_article
kaiming_init: True
embedding_len: 16
# Lp-norm
embedding_normalization_type: lp # * Matters a little bit
lp_norm: 2

embedding_multiplier: 100 # * This might matter because of numerical accuracy

