#? Creation
name: anomality_detection_arotor_replication

#? Data

data: ARotor_replication

# ! Only single sensor support
query_sensors: [torque1]
# query_sensors: [acc3]

query_rpms: [500, 750, 1250, 1500]

query_torques: [1, 6, 11]

query_installations: [1, 2]

query_baseline_GPs: [1, 2, 3, 4, 5, 6, 7, 8, 9]

query_severities: [mild, severe]

query_faults: [baseline, pitting, wear, micropitting, tff]

window_width: 4328

#? Model

model: prototypical
backbone: InceptionTime
# model_weight_dir: AD_ARotor_replication_torque1_article
model_weight_dir: AD_ARotor_replication_acc3_article
kaiming_init: True
embedding_len: 16
# Lp-norm
embedding_normalization_type: lp # * Matters a little bit
lp_norm: 2

embedding_multiplier: 100 # * This might matter because of numerical accuracy

