train_rpm: [750, 1250]
validation_rpm: [500]
test_rpm: [1500]
train_torques: [1]
validation_torques: [1]
test_torques: [6]
train_installations: [2]
validation_installations: [2]
test_installations: [1, 2]
train_severities: [mild]
validation_severities: [mild]
test_severities: [mild, severe]
