train_rpm: [500, 1500]
validation_rpm: [750]
test_rpm: [1250]
train_torques: [6]
validation_torques: [6]
test_torques: [11]
train_installations: [1]
validation_installations: [1]
test_installations: [1, 2]
train_severities: [severe]
validation_severities: [severe]
test_severities: [mild, severe]
