train_rpm: [500, 1500]
validation_rpm: [1250]
test_rpm: [750]
train_torques: [11]
validation_torques: [11]
test_torques: [1]
train_installations: [1]
validation_installations: [1]
test_installations: [1, 2]
train_severities: [mild]
validation_severities: [mild]
test_severities: [mild, severe]
