train_rpm: [500, 1500]
validation_rpm: [1250]
test_rpm: [750]
train_torques: [6]
validation_torques: [6]
test_torques: [11]
train_installations: [2]
validation_installations: [2]
test_installations: [1, 2]
train_severities: [mild]
validation_severities: [mild]
test_severities: [mild, severe]
