#? Creation
name: anomality_detection
log: false
save: true
eval_freq: 7 # * Decrease for hyper opt and final testing
# eval_episodes: 1 # * Increase for hyper opt and final testing
eval_episodes: 50 # * Increase for hyper opt and final testing
# eval_episodes: 4 # * Increase for hyper opt and final testing
test_episodes: 50

#? Fewshot setup

k_shot: 1
# n_way: 4
n_way: 5
n_query: 36
mix_severities: false # * Baseline measurements use GPs
mix_rpms: false
mix_torques: false
mix_installations: false # * Baseline measurements use GPs
mix_sensors: false
separate_query_and_support: false

#? Data

data: ARotor_replication
train_sensors: [torque1]
validation_sensors: [torque1]
test_sensors: [torque1]

train_rpm: [500, 750, 1250, 1500]
validation_rpm: [500, 1250]
test_rpm: [500, 1250]

train_torques: [1, 6, 11]
validation_torques: [6]
test_torques: [6]

train_installations: [1, 2]
validation_installations: [1, 2]
test_installations: [1, 2]

train_baseline_GPs: [1, 2, 3, 4, 5]
validation_baseline_GPs: [6, 7, 8, 9]
test_baseline_GPs: [6, 7, 8, 9]

train_severities: [severe]
validation_severities: [mild]
test_severities: [mild]

train_faults: [baseline, pitting, wear, micropitting, tff]
validation_faults: [baseline, pitting, wear, micropitting, tff]
test_faults: [baseline, pitting, wear, micropitting, tff]

window_width: 4328
window_overlap: 0.99

#? Preprocessing

preprocessing_full: []
robust_scaling_low: 0.25
robust_scaling_high: 0.75
preprocessing_sample: []
preprocessing_class_batch: []
preprocessing_batch: [gain_changer, add_white_noise]
include_FFT_DC: false # Should the DC component of the FFC be included? Only relevant if FFT is used in some form
log_FFT: false
pad_FFT: -1
sample_cut: -1 # Done in batch preprocessing

#? Model

model: prototypical
backbone: InceptionTime
kaiming_init: True
embedding_len: 16
# Lp-norm
embedding_normalization_type: lp
lp_norm: 2

embedding_multiplier: 100

#? Training

epoch_len: 1
max_epochs: 85
patience: 30
optimizer: AdamW

# Torque1
lr: 0.0010516114088954859
lr_scheduler: ExponentialLR
sch_gamma: 0.9516205212854265
momentum: 0.9608964925174016
# Augmentation
gain_std: 0.3
white_noise_std: 0.1
# Regularization
weight_decay: 1.2554141358856704e-05
label_smoothing: 0.0
cl_dropout: 0.0
fc_dropout: 0.0

# Acc3
# lr: 0.0010516114088954859
# lr_scheduler: ExponentialLR
# sch_gamma: 0.9516205212854265
# momentum: 0.9608964925174016
# # Augmentation
# gain_std: 0.3
# white_noise_std: 0.3
# # Regularization
# weight_decay: 1.2554141358856704e-05
# label_smoothing: 0.0
# cl_dropout: 0.0
# fc_dropout: 0.0

# ? Other

use_amp: false
