#? Creation
name: result_generation
log: false
save: false
eval_freq: 7 # * Decrease for hyper opt and final testing
eval_episodes: 50 # * Increase for hyper opt and final testing
test_episodes: 100

#? Fewshot setup

k_shot: 1
# n_way: 4
n_way: 5
n_query: 36
mix_severities: false # * Baseline measurements use GPs
mix_rpms: false
mix_torques: false
mix_installations: false # * Baseline measurements use GPs
mix_sensors: false
separate_query_and_support: false

#? Data

data: ARotor_replication
train_sensors: [torque1]
validation_sensors: [torque1]
test_sensors: [torque1]
# train_sensors: [acc3]
# validation_sensors: [acc3]
# test_sensors: [acc3]

# Overriden
# train_rpm: [750, 1250]
# validation_rpm: [500, 1500]
# test_rpm: [500, 1500]

# train_torques: [1, 11]
# validation_torques: [11]
# test_torques: [6]

# train_installations: [1]
# validation_installations: [1, 2]
# test_installations: [1, 2]

train_baseline_GPs: [1, 2, 3]
validation_baseline_GPs: [4, 5]
test_baseline_GPs: [6, 7, 8, 9]

# train_severities: [severe]
# validation_severities: [mild]
# test_severities: [mild]

train_faults: [baseline, pitting, wear, micropitting, tff]
validation_faults: [baseline, pitting, wear, micropitting, tff]
test_faults: [baseline, pitting, wear, micropitting, tff]

window_width: 4328
window_overlap: 0.99

#? Preprocessing

preprocessing_full: []
robust_scaling_low: 0.25
robust_scaling_high: 0.75
preprocessing_sample: []
preprocessing_class_batch: []
preprocessing_batch: [gain_changer, add_white_noise]
include_FFT_DC: false # Should the DC component of the FFC be included? Only relevant if FFT is used in some form
log_FFT: false
pad_FFT: -1
sample_cut: -1 # Done in batch preprocessing

#? Model

model: prototypical
backbone: InceptionTime
# backbone: WDCNN
kaiming_init: True
embedding_len: 16
# Lp-norm
embedding_normalization_type: lp
lp_norm: 2

embedding_multiplier: 100

#? Training

epoch_len: 1
max_epochs: 85
patience: 30
optimizer: AdamW

# Torque1
lr: 0.0063049118460096094
lr_scheduler: ExponentialLR
sch_gamma: 0.9731748731285381
momentum: 0.9317683073517322
# Augmentation
gain_std: 0.3
white_noise_std: 0.1
# Regularization
weight_decay: 0.000251643104874755
label_smoothing: 0.0
cl_dropout: 0.0
fc_dropout: 0.0

# # Acc3
# lr: 0.0005223477208678914
# lr_scheduler: ExponentialLR
# sch_gamma: 0.9934610488065857
# momentum: 0.9059946433455243
# # Augmentation
# gain_std: 0.3
# white_noise_std: 0.3
# # Regularization
# weight_decay: 0.0002240641976452195
# label_smoothing: 0.0
# cl_dropout: 0.0
# fc_dropout: 0.0

# ? Other

use_amp: false
