#? Creation
name: SR2SR
log: true
save: false # TODO
eval_freq: 10 # * Decrease for hyper opt and final testing
eval_episodes: 10 # * Increase for hyper opt and final testing

#? Fewshot setup

k_shot: 1
n_way: 10
n_query: 24
mix_rpms: false
mix_sensors: false
separate_query_and_support: false

#? Data

data: ARotor
# train_sensors: [torque2]
# validation_sensors: [torque2]
# test_sensors: [torque1]
# train_sensors: [en1acc]
# validation_sensors: [en2acc]
# test_sensors: [en3acc, en4acc, en5acc]
train_sensors: [en1acc_grad]
validation_sensors: [en2acc_grad]
test_sensors: [en3acc_grad, en4acc_grad, en5acc_grad]
train_rpm: [750]
validation_rpm: [1000]
test_rpm: [250, 500, 1250, 1500]
train_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
validation_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
test_classes: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
window_width: 6000
window_overlap: 0.95

#? Preprocessing

preprocessing_full: []
preprocessing_sample: []
# preprocessing_sample: [FFT]
# preprocessing_sample: [sync_FFT] # ! Slow, always prefer the other two if possible
sync_FFT_rotations: 4 # How many rotations to include for synced FFT. Only used if sync_FFT on.
# preprocessing_batch: []
# preprocessing_batch: [FFT]
preprocessing_batch: [sync_FFT]
include_FFT_DC: false # Should the DC component of the FFC be included? Only relevant if FFT is used in some form

# FFT: true
# embedding_unit_len: true
# rpm_status: batch
# sensor_status: batch
# normalize: false

#? Augmentation

augmentation: []

#? Model

model: prototypical
backbone: mininet
kaiming_init: true
embedding_len: 512
# embedding_normalization_type: False
# Legacy
# embedding_normalization_type: old
# Lp-norm
embedding_normalization_type: lp
lp_norm: 2
# Mahalanobis
# embedding_normalization_type: mahalanobis # TODO

embedding_multiplier: 100

#? Training

epoch_len: 10
max_epochs: 600
patience: 100
optimizer: AdamW
lr: 0.0009965
lr_scheduler: ExponentialLR
# sch_gamma: 0.9999999
sch_gamma: 0.9782
momentum: 0.9823
# Regularization
weight_decay: 0.00002995
# weight_decay: 0.0001
cl_dropout: 0.0
fc_dropout: 0.0

# ? Other

use_amp: false